set(CMAKE_CXX_FLAGS_DEBUG  "${CMAKE_CXX_FLAGS_DEBUG} -DDEBUG")
set(CMAKE_CXX_STANDARD 17)

if (WIN32)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHsc")
    if (MSVC_VERSION GREATER_EQUAL 1910) # VS 2017
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /openmp")
    endif()
endif()

if (APPLE)
    set(CMAKE_INSTALL_RPATH /Users/bdavis/VulkanSDK/1.1.85.0/macOS/lib/)
    set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
endif()

